- name: Initial Playbook
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: run show ip interface brief
      ios_command:
        commands:
          - show ip int br
      register: sh_ip_int_br_result

    - name: Debug registered var
      debug:
        var: sh_ip_int_br_result.stdout_lines
